import Head from 'next/head'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import {useTranslation} from "next-i18next";
import {NextPageWithLayout} from "@/pages/_app";
import {getLayout} from "@/layouts/site-layout";



const Home: NextPageWithLayout = () => {
  const {t} = useTranslation("common");
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {t("hello")}
      </div>
    </>
  )
}

type Props = {
  locale: any,
}
export async function getStaticProps({ locale }: Props) {
  return {
    props: {
      ...(await serverSideTranslations(locale, [
        'common',
      ])),
      // Will be passed to the page component as props
    },
  }
}

Home.getLayout = getLayout;


export default Home;
